apiVersion: 1

datasources:
  - name: PostgreSQL-Crypto
    type: postgres
    uid: postgres
    access: proxy
    url: postgres-db:5432
    database: crypto_data
    user: user
    secureJsonData:
      password: 'password'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: false
    isDefault: true
    editable: true
